#Nome da aplica��o
spring.application.name=habito
#Configura��o BD
spring.datasource.url=jdbc:mysql://localhost:3306/habito?serverTimezone=UTC
spring.profiles.active=local
#Configura��o ORM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true